var fs = require('fs');
var code = fs.readFileSync('index.js', 'utf8');

var newFunc = [
'function findEpisodeFile(files, season, episode) {',
'    if (!files || files.length === 0) return null;',
'    var s = String(season).padStart(2, "0");',
'    var e = String(episode).padStart(2, "0");',
'    var ep = parseInt(episode);',
'    var se = parseInt(season);',
'    var videoExts = [".mkv",".mp4",".avi",".mov",".wmv",".m4v"];',
'    var videoFiles = files.filter(f => videoExts.some(ex => (f.path||"").toLowerCase().endsWith(ex)));',
'    var searchIn = videoFiles.length > 0 ? videoFiles : files;',
'    console.log("[findEpisode] Tim S" + s + "E" + e + " trong " + searchIn.length + " files");',
'    searchIn.forEach(f => console.log("  File: " + (f.path||"")));',
'    var patterns = [',
'        new RegExp("S" + s + "E" + e + "[^0-9]", "i"),',
'        new RegExp("S" + s + "E" + e + "$", "i"),',
'        new RegExp("S" + s + "[.]E" + e, "i"),',
'        new RegExp(se + "x" + e, "i"),',
'        new RegExp("[._-]" + s + e + "[._-]"),',
'        new RegExp("Episode[._ ]?" + ep + "[^0-9]", "i"),',
'        new RegExp("Ep[._ ]?" + e + "[^0-9]", "i")',
'    ];',
'    for (var i = 0; i < patterns.length; i++) {',
'        for (var j = 0; j < searchIn.length; j++) {',
'            var filename = (searchIn[j].path || "").split("/").pop();',
'            if (patterns[i].test(filename)) {',
'                console.log("[findEpisode] Match: " + filename);',
'                return searchIn[j];',
'            }',
'        }',
'    }',
'    var seasonFiles = searchIn.filter(f => {',
'        var fullPath = (f.path || "").toLowerCase();',
'        return fullPath.indexOf("season " + se) !== -1 ||',
'               fullPath.indexOf("season" + se) !== -1 ||',
'               fullPath.indexOf("/s" + s + "/") !== -1 ||',
'               fullPath.indexOf("season_" + se) !== -1;',
'    });',
'    console.log("[findEpisode] Files Season " + se + ": " + seasonFiles.length);',
'    if (seasonFiles.length > 0) {',
'        for (var i = 0; i < patterns.length; i++) {',
'            for (var j = 0; j < seasonFiles.length; j++) {',
'                if (patterns[i].test(seasonFiles[j].path || "")) {',
'                    console.log("[findEpisode] Match fullpath: " + seasonFiles[j].path);',
'                    return seasonFiles[j];',
'                }',
'            }',
'        }',
'        var sorted = seasonFiles.sort((a, b) => (a.path||"").toLowerCase().localeCompare((b.path||"").toLowerCase()));',
'        for (var j = 0; j < sorted.length; j++) {',
'            var fname = (sorted[j].path || "").split("/").pop();',
'            var m1 = fname.match(/(?:ep|episode)[._ ]?0*(\\d+)/i);',
'            var m2 = fname.match(/[._-]0*(\\d+)[._-]/);',
'            var m3 = fname.match(/^0*(\\d+)[._-]/);',
'            var matched = m1 || m2 || m3;',
'            if (matched && parseInt(matched[1]) === ep) {',
'                console.log("[findEpisode] Match ep number: " + fname);',
'                return sorted[j];',
'            }',
'        }',
'        if (ep <= sorted.length) {',
'            console.log("[findEpisode] Fallback index: " + sorted[ep-1].path);',
'            return sorted[ep - 1];',
'        }',
'    }',
'    console.log("[findEpisode] Khong tim thay!");',
'    return null;',
'}'
].join('\n');

var oldMatch = code.match(/function findEpisodeFile[\s\S]*?\nfunction /);
if (!oldMatch) { console.log('Khong tim thay ham cu!'); process.exit(1); }

var oldFunc = oldMatch[0].replace(/\nfunction $/, '');
code = code.replace(oldFunc, newFunc + '\n');
fs.writeFileSync('index.js', code);
console.log('Fix thanh cong!');
